Banislav/bot configuration
banislav/Price-Bot pull request #4
Opened 2022-09-18 20:01 UTC by banislav

Need code review from **_PAPA_**

2022-09-18 22:22 UTC, sexozavr requested changes
в целом норм, за исключением того, что когда какая-то хуйня в боте случается, ты не отсылаешь юзера на start_message (либо это фича и я долбоеб)

2022-09-18 22:22 UTC, sexozavr commented on main.py
> +    bot.send_message(message.chat.id, text, reply_markup=keyboard_markup)
вот тут я бы хэндлер добавил, а не просто сообщение отсылал

2022-09-18 22:22 UTC, sexozavr commented on main.py
> +            bot.send_message(message.chat.id, cfg.UNKNOWNCOMMAND_MESSAGE)
давай после того как чел какую-то непонятную хуйню высрал его нa start_message возвращать, а не просто сообщение слать

2022-09-18 22:22 UTC, sexozavr commented on main.py
> +    start_message(message, 'Anything else I can do for you?')
тут сообщение в конфиг можно вынести

2022-09-18 22:22 UTC, sexozavr commented on main.py
> +    start_message(message, 'Anything else I can do for you?')
same

2022-09-18 22:22 UTC, sexozavr commented on main.py
> +        bot.send_message(message.chat.id, cfg.NOTFOUND_MESSAGE)
здесь опять же надо отсылать на start_message

2022-09-18 22:22 UTC, sexozavr commented on scraping/parser.py
>              sleep(2)
количество секунд здесь сунуть либо в конфиг, либо в аргументы

2022-09-19 11:55 UTC, banislav commented on main.py
> +    bot.send_message(message.chat.id, text, reply_markup=keyboard_markup)
а я нет

2022-09-19 11:58 UTC, banislav commented on main.py
> +        bot.send_message(message.chat.id, cfg.NOTFOUND_MESSAGE)
Я итак отсылаю, выше по стеку вызовов посмотри

2022-09-19 12:05 UTC, banislav commented
> в целом норм, за исключением того, что когда какая-то хуйня в боте случается, ты не отсылаешь юзера на start_message (либо это фича и я долбоеб)

2022-09-19 12:05 UTC, closed without merging